language: node_js
sudo: required
cache:
  directories:
  - node_modules
branches:
  except:
  - master
node_js:
- '6.1'
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- rvm install 2.1
- rvm use 2.1
- . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
- gem install bundler
- bundle check || bundle install
before_script:
- npm install -g gulp
- ls
- pwd
- chmod +x ./_scripts/build.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: EEUVxqnPP9zur2X1Mwv6r+mv0YdKzHjLHdOP9zpMLntZXyb4cgTvcS3P+ARsqIbjopv25nIiQMbSd78slqdhW6JUh0UvnDnJ5ggpmTla1q4o4PLCnYsfLo//4lEPy1opqRNoqf0wQfrSHTtsP7zBGsb82GvacMOrVLAmM+Q7xBDghBBoP9AO/QZ7McHGrIN+YUkZdaRxs4fQRBCOcXFyG9zN2LDc/J5OoGIZteB4HDmHexwCBEnCNIPFbSltn1CTkIinfnwx1WB59AyHo7HEDXhwvcqIyj+JgJi87q+YSAT4OV/6zfbqKTuepLiaJC22/7Kv1LwNnWHM5qcx9lkzW3hqkn4k4fa5d0HH8jvj6xJuBUM0KOJS1UJSrK7L1IDbgGpI4K7UDfxUT7bnaY2BF3VunjTmpKqi6hhc/Tb+atLXyj7P3LMIiFP5m0ISpzmv50HT5rscyGpRoz1xBLPTvFbT8/PPshZ0YfYyXYiP7b42dX4Jjv1dchqJ7r7tvnX2S8J5vI+NU7VRnIawna2XV1MVuoP2FDg8k7nv7CwTbXHbmjurKw6qx1MjDix3qzMREKZCBiSRt7uFbuyt5+fbknryVkoN7zHe4VchDKESZ3U1kvieGWMn+ChrqnQlvCzaOd1SyyLgCxyEWWFudSDcJdpcqHDNE3MRATo5ZSOqZYY=
  - secure: fYEf6I30zUIOfc3IXvSJN/emV1AeWeJraMFhlCUx42UaZwN55irBf+J4Y1oKHoOMZ/GFKHVICi9dya0+I3IbwqvI5oCjBNVzd0GC0I7HBSjh78PmnYaIh6UoTmk/YS1f3Ezh9dICMmMtcsEtO5q42NtMrzpnUC+xQqOtNaCqgeuZREPogrq6Gb7x6LW1QvDCJfUHRsm5j6+UQlBiv4qp+7e170UJ+kvKnYdAB6uGBNsPlWZO3LQbGjVRCMlZr6flwbjJ5lOhpuTFAnCXosICbSCdckqYlEM2K61dvc+I9UUWqa9lOv1qdFnMlee4GMOewfN0+lE0I74LmVcVFe6ihaZOAZMXeXoQuiVCvYRWMcyjAP6swkvoC23kXxvQCx0sNT/5H7kgM9+kjuz+j9jfsSj1PGvVe0RStXYimO30M3IQlYAkbCLEttTDDznVD2VTQlIy3tfD5D1FCvpbGMHcy10vUlYr+dP9sg+Cxd7kLl23ZrnSaw9sE6X6P0EZHI8GMkvmt2Xs9+PBIOTucOFAWNyuHN3EZ+ggnatVb58XxMC4XEALUogm5O2+Efvwo4emqGxT1KBN65XwSUtBSBXwf8Lh3ZMO2bxz2SijNJoLfjTL4a22k0iIo8ljtAGCi8qYYkPktmNbtbylWX2qFNAKuXi2XK0O5H4CW+LA7Kz28Vc=
script: ./_scripts/build.sh
skip_cleanup: false
true:
  branch: source
