---
title: jekyll-starter-kit
repository: /jekyll-starter-kit
timezone: UTC
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - _assets
  - node_modules  
sass:
  style: compressed
include:
- _pages
prose:
  media: assets/img
  metadata:
    _posts:
      - name: "blog_description"
        field:
          label: "Description"
          element: "textarea"
          placeholder: "Enter a Description"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An awesome Headline!"
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "blog_detail"
      - name: "blog_category"
        field:
          label: "Category"
          element: "text"
          value: ""
      - name: "thumbnail"
        field:
          label: "Blog Image"
          element: "text"
          value: ""
      - name: "blog_highlight"
        field:
          label: "Blog Highlight"
          element: "textarea"
          value: ""
      - name: "date"
        field:
          label: "Date"
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "author_name"
        field:
          label: "Author name"
          element: "select"
          value: "true"
          options:
             - name: 'author name'
               value: 'author value'
                 